import { LifeEvent } from './types';

export const events: LifeEvent[] = [
  {
    id: "1",
    date: "1869-10-02",
    year: 1869,
    title: "Birth of Mohandas",
    description: "Mohandas Karamchand Gandhi is born in Porbandar, a coastal town in Gujarat, India.",
    location: "Porbandar, Gujarat",
    lat: 21.6417,
    lng: 69.6293,
    type: "birth",
    chapter: "Early Life",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Gandhi_1876.jpg/440px-Gandhi_1876.jpg"]
  },
  {
    id: "2",
    date: "1876-01-01",
    year: 1876,
    title: "Move to Rajkot",
    description: "His father Karamchand becomes the Diwan (Prime Minister) of Rajkot state. The family moves.",
    location: "Rajkot, Gujarat",
    lat: 22.3039,
    lng: 70.8022,
    type: "travel",
    chapter: "Early Life"
  },
  {
    id: "3",
    date: "1888-09-04",
    year: 1888,
    title: "Voyage to London",
    description: "Gandhi sails to England to study law at University College London, defying caste restrictions.",
    location: "London, UK",
    lat: 51.5074,
    lng: -0.1278,
    type: "travel",
    chapter: "Early Life",
    images: ["https://upload.wikimedia.org/wikipedia/commons/3/3e/Gandhi_London_1906.jpg"]
  },
  {
    id: "4",
    date: "1891-06-12",
    year: 1891,
    title: "Called to the Bar",
    description: "He is called to the Bar at the Inner Temple and returns to India shortly after.",
    location: "Mumbai, India",
    lat: 18.9388,
    lng: 72.8354,
    type: "travel",
    chapter: "Early Life"
  },
  {
    id: "5",
    date: "1893-05-23",
    year: 1893,
    title: "Arrival in South Africa",
    description: "Gandhi arrives in Durban to handle a legal case for Dada Abdulla & Co.",
    location: "Durban, South Africa",
    lat: -29.8587,
    lng: 31.0218,
    type: "travel",
    chapter: "South Africa"
  },
  {
    id: "6",
    date: "1893-06-07",
    year: 1893,
    title: "The Pietermaritzburg Incident",
    description: "Thrown off a train for refusing to leave the first-class compartment, a turning point in his life.",
    location: "Pietermaritzburg, South Africa",
    lat: -29.6006,
    lng: 30.3794,
    type: "movement",
    chapter: "South Africa"
  },
  {
    id: "7",
    date: "1894-08-22",
    year: 1894,
    title: "Natal Indian Congress",
    description: "Establishes the Natal Indian Congress to fight discrimination against Indians in South Africa.",
    location: "Durban, South Africa",
    lat: -29.8587,
    lng: 31.0218,
    type: "movement",
    chapter: "South Africa"
  },
  {
    id: "8",
    date: "1904-12-01",
    year: 1904,
    title: "Phoenix Settlement",
    description: "Establishes his first ashram, the Phoenix Settlement, experimenting with communal living.",
    location: "Inanda, South Africa",
    lat: -29.7126,
    lng: 30.9782,
    type: "movement",
    chapter: "South Africa"
  },
  {
    id: "9",
    date: "1906-09-11",
    year: 1906,
    title: "First Satyagraha",
    description: "Adopts the methodology of Satyagraha (devotion to truth) for the first time at the Empire Theatre in Johannesburg.",
    location: "Johannesburg, South Africa",
    lat: -26.2041,
    lng: 28.0473,
    type: "movement",
    chapter: "South Africa",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Gandhi_South_Africa.jpg/440px-Gandhi_South_Africa.jpg"]
  },
  {
    id: "10",
    date: "1908-01-10",
    year: 1908,
    title: "First Imprisonment",
    description: "Gandhi is jailed for the first time for refusing to carry registration passes.",
    location: "Johannesburg, South Africa",
    lat: -26.1751,
    lng: 28.0350,
    type: "arrest",
    chapter: "South Africa"
  },
  {
    id: "11",
    date: "1910-05-30",
    year: 1910,
    title: "Tolstoy Farm",
    description: "Establishes Tolstoy Farm, a second commune for Satyagrahis.",
    location: "Lawley, South Africa",
    lat: -26.3486,
    lng: 27.8384,
    type: "movement",
    chapter: "South Africa"
  },
  {
    id: "12",
    date: "1915-01-09",
    year: 1915,
    title: "Return to India",
    description: "Returns to India permanently. Crowds welcome him at Apollo Bunder.",
    location: "Mumbai, India",
    lat: 18.9220,
    lng: 72.8347,
    type: "travel",
    chapter: "Freedom Struggle"
  },
  {
    id: "13",
    date: "1915-05-25",
    year: 1915,
    title: "Kochrab Ashram",
    description: "Establishes his first ashram in India near Ahmedabad.",
    location: "Ahmedabad, Gujarat",
    lat: 23.0120,
    lng: 72.5590,
    type: "movement",
    chapter: "Freedom Struggle"
  },
  {
    id: "14",
    date: "1917-04-10",
    year: 1917,
    title: "Champaran Satyagraha",
    description: "Launches his first major civil disobedience movement in India supporting indigo farmers.",
    location: "Champaran, Bihar",
    lat: 26.8467,
    lng: 84.5014,
    type: "movement",
    chapter: "Freedom Struggle"
  },
  {
    id: "15",
    date: "1918-03-22",
    year: 1918,
    title: "Kheda Satyagraha",
    description: "Supports peasants in Kheda who could not pay taxes due to famine.",
    location: "Kheda, Gujarat",
    lat: 22.7533,
    lng: 72.6864,
    type: "movement",
    chapter: "Freedom Struggle"
  },
  {
    id: "16",
    date: "1919-04-13",
    year: 1919,
    title: "Jallianwala Bagh Response",
    description: "Following the massacre, Gandhi organizes protests and returns British honors.",
    location: "Amritsar, Punjab",
    lat: 31.6209,
    lng: 74.8797,
    type: "movement",
    chapter: "Freedom Struggle"
  },
  {
    id: "17",
    date: "1920-08-01",
    year: 1920,
    title: "Non-Cooperation Movement",
    description: "Launches nationwide Non-Cooperation Movement inciting Indians to boycott British goods and institutions.",
    location: "Kolkata, West Bengal",
    lat: 22.5726,
    lng: 88.3639,
    type: "movement",
    chapter: "Freedom Struggle"
  },
  {
    id: "18",
    date: "1922-02-04",
    year: 1922,
    title: "Chauri Chaura Incident",
    description: "Calls off the Non-Cooperation movement after a mob sets fire to a police station.",
    location: "Chauri Chaura, UP",
    lat: 26.6508,
    lng: 83.5936,
    type: "movement",
    chapter: "Freedom Struggle"
  },
  {
    id: "19",
    date: "1922-03-10",
    year: 1922,
    title: "Arrest and Trial",
    description: "Arrested for sedition and sentenced to six years in prison at Yerwada Jail.",
    location: "Pune, Maharashtra",
    lat: 18.5580,
    lng: 73.8906,
    type: "arrest",
    chapter: "Freedom Struggle"
  },
  {
    id: "20",
    date: "1924-02-05",
    year: 1924,
    title: "Release from Prison",
    description: "Released early on medical grounds after an appendicitis operation.",
    location: "Pune, Maharashtra",
    lat: 18.5204,
    lng: 73.8567,
    type: "travel",
    chapter: "Freedom Struggle"
  },
  {
    id: "21",
    date: "1930-03-12",
    year: 1930,
    title: "Salt March Begins",
    description: "Begins the historic Dandi March from Sabarmati Ashram to protest the salt tax.",
    location: "Sabarmati Ashram, Ahmedabad",
    lat: 23.0596,
    lng: 72.5804,
    type: "movement",
    chapter: "Freedom Struggle",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Gandhi_Salt_March.jpg/640px-Gandhi_Salt_March.jpg"]
  },
  {
    id: "22",
    date: "1930-04-06",
    year: 1930,
    title: "Breaking the Salt Law",
    description: "Reaches Dandi and breaks the salt law by picking up a lump of natural salt.",
    location: "Dandi, Gujarat",
    lat: 20.8880,
    lng: 72.8009,
    type: "movement",
    chapter: "Freedom Struggle"
  },
  {
    id: "23",
    date: "1931-08-29",
    year: 1931,
    title: "Round Table Conference",
    description: "Sails to London to attend the Second Round Table Conference as the sole representative of Congress.",
    location: "London, UK",
    lat: 51.5007,
    lng: -0.1246,
    type: "travel",
    chapter: "Freedom Struggle"
  },
  {
    id: "24",
    date: "1932-09-20",
    year: 1932,
    title: "Epic Fast at Yerwada",
    description: "Begins a fast unto death in Yerwada Jail against separate electorates for 'untouchables'.",
    location: "Pune, Maharashtra",
    lat: 18.5580,
    lng: 73.8906,
    type: "movement",
    chapter: "Freedom Struggle"
  },
  {
    id: "25",
    date: "1936-04-30",
    year: 1936,
    title: "Sevagram Ashram",
    description: "Moves his headquarters to a small village in central India, naming it Sevagram.",
    location: "Wardha, Maharashtra",
    lat: 20.7299,
    lng: 78.6044,
    type: "movement",
    chapter: "Freedom Struggle"
  },
  {
    id: "26",
    date: "1942-08-08",
    year: 1942,
    title: "Quit India Speech",
    description: "Delivers the 'Do or Die' speech at Gowalia Tank Maidan, launching the Quit India Movement.",
    location: "Mumbai, Maharashtra",
    lat: 18.9623,
    lng: 72.8122,
    type: "speech",
    chapter: "Freedom Struggle"
  },
  {
    id: "27",
    date: "1942-08-09",
    year: 1942,
    title: "Agakhan Palace Arrest",
    description: "Arrested along with wife Kasturba and secretary Mahadev Desai; held at Aga Khan Palace.",
    location: "Pune, Maharashtra",
    lat: 18.5524,
    lng: 73.9022,
    type: "arrest",
    chapter: "Freedom Struggle"
  },
  {
    id: "28",
    date: "1944-02-22",
    year: 1944,
    title: "Death of Kasturba",
    description: "His wife Kasturba Gandhi passes away while imprisoned at Aga Khan Palace.",
    location: "Pune, Maharashtra",
    lat: 18.5524,
    lng: 73.9022,
    type: "death",
    chapter: "Freedom Struggle"
  },
  {
    id: "29",
    date: "1946-11-06",
    year: 1946,
    title: "Noakhali Peace Mission",
    description: "Walks barefoot through riot-torn villages in Noakhali (now Bangladesh) to restore peace.",
    location: "Noakhali, Bangladesh",
    lat: 22.8422,
    lng: 91.0967,
    type: "movement",
    chapter: "Independence"
  },
  {
    id: "30",
    date: "1947-08-15",
    year: 1947,
    title: "Independence Day",
    description: "While India celebrates independence, Gandhi fasts in Kolkata to stop communal rioting.",
    location: "Kolkata, West Bengal",
    lat: 22.5629,
    lng: 88.3962,
    type: "movement",
    chapter: "Independence",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Gandhi_Jinnah_1944.jpg/440px-Gandhi_Jinnah_1944.jpg"]
  },
  {
    id: "31",
    date: "1948-01-13",
    year: 1948,
    title: "Final Fast",
    description: "Undertakes his last fast in Delhi to pressure India to pay Pakistan's dues and stop violence.",
    location: "Delhi, India",
    lat: 28.6019,
    lng: 77.2144,
    type: "movement",
    chapter: "Final Days"
  },
  {
    id: "32",
    date: "1948-01-30",
    year: 1948,
    title: "Assassination",
    description: "Shot three times by Nathuram Godse at Birla House while on his way to prayer.",
    location: "Birla House, Delhi",
    lat: 28.6019,
    lng: 77.2144,
    type: "death",
    chapter: "Final Days"
  }
];
